### ISSUE TITLE
"big_int" deprecated

### ISSUE THREAD

**Issue by kojix2** [Nephos/stats#1]
Hello. 

I got Error.
Error: while requiring "big_int": can't find
https://github.com/crystal-lang/crystal/pull/5121

**Comment by Nephos** [comment]
Thank you, it's merged :)

**Comment by pyrokar** [comment]
Could you please tag this commit as a new version?

Thank you :-)

**Comment by Nephos** [comment]
Done: https://github.com/Nephos/stats/releases/tag/v0.2.2 :)
